spring.application.name=Library-Management-System

server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5432/library-management
spring.datasource.username=librarymanager
spring.datasource.password=librarypassword
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
